import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# ---- Step 1: Load result files ----
# Filenames (ensure these are generated by your previous modules)
burn_img_path = 'burn_detected.png'
change_img_path = 'change_mask.png'
ownership_img_path = 'ownership_risk_visualization.png'
govt_csv_path = 'govt_risk_mask.csv'
private_csv_path = 'private_risk_mask.csv'

assert all([os.path.exists(p) for p in [burn_img_path, change_img_path, ownership_img_path, govt_csv_path, private_csv_path]]), "One or more required files missing!"

# ---- Step 2: Calculate key statistics ----
# Burned area percentage
burn_img = cv2.imread(burn_img_path, 0)
burned_pixels = np.sum(burn_img > 20)  # Tune threshold as needed
total_pixels = burn_img.size
burn_pct = burned_pixels / total_pixels * 100

# Risk ownership stats
govt_risk_mask = np.loadtxt(govt_csv_path, delimiter=',')
private_risk_mask = np.loadtxt(private_csv_path, delimiter=',')
govt_risk_count = int(np.sum(govt_risk_mask))
private_risk_count = int(np.sum(private_risk_mask))

# ---- Step 3: Combine results into one summary image ----
img_files = [burn_img_path, change_img_path, ownership_img_path]
titles = ["Burn Area", "Change Detection", "Ownership Risk"]

plt.figure(figsize=(14,5))
for idx, img_file in enumerate(img_files):
    img = cv2.imread(img_file)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.subplot(1, len(img_files), idx + 1)
    plt.imshow(img_rgb)
    plt.title(titles[idx])
    plt.axis('off')
plt.tight_layout()
plt.savefig('project_summary.png')
plt.close()

# ---- Step 4: Generate the Markdown/Text Report ----
with open("project_report.md", "w") as report:
    report.write("# Forest Monitoring & Risk Layer Project\n\n")
    report.write("## Project Summary\n")
    report.write("- Burned area detected and quantified\n")
    report.write("- Change detection mapped\n")
    report.write("- Risk layer generated and ownership overlay completed\n")
    report.write("\n## Key Statistics\n")
    report.write(f"- **Total burned area:** {burn_pct:.2f}% of image\n")
    report.write(f"- **Risky area on government land:** {govt_risk_count} pixels\n")
    report.write(f"- **Risky area on private land:** {private_risk_count} pixels\n")
    report.write("\n## Outputs\n")
    report.write("- [project_summary.png](project_summary.png): Visual overview (burn/chg/ownership)\n")
    report.write(f"- [govt_risk_mask.csv](govt_risk_mask.csv): Risk mask (govt parcels)\n")
    report.write(f"- [private_risk_mask.csv](private_risk_mask.csv): Risk mask (private parcels)\n")
    report.write("\n## Methodology\n")
    report.write(
        "1. Preprocessed images and extracted burned areas\n"
        "2. Detected change zones by differencing\n"
        "3. Generated risk map by fusing all detection results\n"
        "4. Overlaid ownership to identify at-risk parcels\n"
        "5. Automated summary report generation for review and handover\n"
    )
    report.write("\n---\n")
    report.write("**Prepared automatically by Python scripts for final submission.**\n")

print("Report created as 'project_report.md', and summary figure as 'project_summary.png'.")
print(f"Burned area: {burn_pct:.2f}% | Govt risk pixels: {govt_risk_count} | Private risk pixels: {private_risk_count}")
print("Ready for submission. All files are present for dashboard and documentation.")
